### ISSUE TITLE
Overloading operators

### ISSUE THREAD

**Issue by noklam** [fastai/fastdot#3]
I made some operator overloading like using + (to add items intuitively). Would this be interested? Of course for more custom case(need more than 1 argument, you would see go back to the add_item()

![image](https://user-images.githubusercontent.com/18221871/75613800-c94bb900-5b6c-11ea-821e-430f351e6d3c.png)
![image](https://user-images.githubusercontent.com/18221871/75613814-d1a3f400-5b6c-11ea-8259-3b36c9632ec1.png)

**Comment by jph00** [comment]
Closing this since we have a PR now.
